site_name: Lockbox iOS
site_description: Documentation for Lockbox's iOS application
theme: readthedocs
repo_name: GitHub
repo_url: https://github.com/mozilla-lockbox/lockbox-ios

pages:
- 'Introduction': 'index.md'
- 'Contributing': 'contributing.md'
- 'Telemetry and Metrics': 'metrics.md'
- 'Developer Guides':
  - 'Build and Install': 'install.md'
  - 'Architecture': 'architecture.md'
  - 'Dependencies': 'updating_libraries.md'
